# Generated by Django 5.2.1 on 2025-05-31 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('app_type', models.CharField(choices=[('SAML', 'SAML'), ('OIDC', 'OIDC')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saml_sso_url', models.URLField(blank=True, null=True)),
                ('saml_entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('saml_relay_state', models.CharField(blank=True, max_length=255, null=True)),
                ('saml_username_template', models.CharField(blank=True, max_length=50, null=True)),
                ('oidc_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_policies', models.TextField(blank=True, null=True)),
                ('configuration_data', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
